### ISSUE TITLE
Comparison to ReactiveNative and React-Style

### ISSUE THREAD

**Issue by newtack** [petehunt/jsxstyle#1]
JSXStyle looks like an awesome solution for ReactJS.

But what is the story if I want to build a solution both for ReactJS and React Native?

There was a comment (twitter?) that if you wanted to reuse your styling information between react js and reactive native that you should use react-style. 

What's the possibility of reuse of JSXStyle for React Native, if not in the immediate but at least in the intermediate future?

What problems does React-Style have that JSXStyle does not?

**Comment by newtack** [comment]
After your edit and re-reading of the readme, I think you answered the question of React-Style (not being inline the component when it really should be part of it). 
How about the ReactiveNative part?

**Comment by petehunt** [comment]
Sorry I forgot to respond to this.

The reason react-style is set up the way that it is is so we can easily generate static stylesheets from it (in theory). We hadn't thought too much about an approach that is more heavy on the static analysis and changes the way styles are expressed, as in this repo. I think if I had stayed at FB, I may have ended up convincing them to go this route :)

I believe @vjeux thinks that styles inside of the `render()` method makes it more cluttered, but I'm not sure if he's actually built an app with it yet :) Once you have higher level layout and style components it becomes pretty slick.
