### ISSUE TITLE
add a line to docs about passing event handlers

### ISSUE THREAD

**Issue by threepointone** [petehunt/jsxstyle#12]
Discovered that I can do this - 
```js
<Flex props={{onClick: ()=> alert('event handlers!') }}/>
```

Very cool! please add a line to the docs to let people know? Please and thanks!

**Comment by hallister** [comment]
That's an arrow function and it works for any project that uses an ES6 shim. But you can define a function inline in ES5 as well:

`<Flex props={{onClick: function() { alert('event handlers!') }.bind(this) }} />`

Regardless, it isn't specific to jsxstyle, it's just ES6.

**Comment by threepointone** [comment]
Sorry if I wasn't clear. Point wasn't about the arrow function, but that I could define event handlers for a Flex component via the `props` prop. This is not mentioned in the docs anywhere.

**Comment by hallister** [comment]
Ah, I see. You can pass any prop via the `props` prop since it's just merging them. However, unless he's recently fixed it I believe there's still a bug such that a `props` tag will be added to your style, so you'll end up with a style tag like `style=...props:[object Object]...`.

**Comment by appsforartists** [comment]
Seems like it should know which props a DOM node accepts and pass those through rather than putting them on `style`.

For instance, `ref`, `key`, and anything starting with `on` should be ignored by `jsxstyle` and passed through unmolested.

**Comment by petehunt** [comment]
More discussion in #32
