### ISSUE TITLE
Flex components do not work in Safari

### ISSUE THREAD

**Issue by sgwilym** [petehunt/jsxstyle#13]
Safari currently only supports Flex with the `-webkit-` prefix. To get Flex components working in Safari you currently have to do the following:

```javascript
<Flex
  display="-webkit-flex">
  I’m a Flexbox that works on Safari!
</Flex>
```
This doesn't fully solve the problem, as Flex related properties (eg. `flexGrow`) would need the same autoprefixing treatment that `userSelect`, `transition`, `boxShadow` and `fontSmoothing` currently get.

Edit: Actually, I'm a bit mystified as to what to do here because adding `display="-webkit-flex"` overrides the display property and breaks flex layouts for Firefox and others. In CSS you can declare multiple `display` properties, which is (sadly) a useful feature in this case. What's the best way to handle this? (related: [this post on StackOverflow, see near the bottom of the original post](https://stackoverflow.com/questions/29438913/prefixing-flexbox-styles-for-react))

**Comment by wmertens** [comment]
I made a thing for that: https://gist.github.com/wmertens/78c840ce04b6e9a1193d

I'd make it into an npm package if someone could tell me what the path of minimum resistance is for setting up an npm repo that needs to compile coffeescript to javascript before updating.

**Comment by KyleAMathews** [comment]
@wmertens put all your coffeescript in a `/src` (or lib or modules or whatever) and [add a prepublish script](https://docs.npmjs.com/misc/scripts) that compiles your code to `/dist`. Point the `main` key in the package.json to `/dist/index.js`

**Comment by petehunt** [comment]
Fixed in https://github.com/petehunt/jsxstyle/commit/b7245649e7d48a0a2a05c7c66a1e2eb3dd153759 ;)
