### ISSUE TITLE
Add support for more elements?

### ISSUE THREAD

**Issue by KyleAMathews** [petehunt/jsxstyle#2]
E.g. `ul`, `li`, etc.

**Comment by petehunt** [comment]
What's the rule for deciding which elements are included and which are excluded? The elements right now correspond with all values for the `display` CSS property.

**Comment by KyleAMathews** [comment]
Wouldn't you want to use this for all elements? From the README it sounds like the goal is to magically extract and optimize all inline styles (when possible) to regular css classes. Why include or not include elements? Ideally this would just happen without having to use funny named replacements for standard DOM components.

**Comment by KyleAMathews** [comment]
So I guess what I'm asking is it possible to react into the guts of React and do what this module does to regular old inline styles? Or is this only possible by creating the wrapper components?

**Comment by petehunt** [comment]
Oh, yes we could do this pretty easily. The reason the wrapper components are nice is 1. I prefer the API (less curly braces) and 2. It separates each property into its own expression, so it's less likely people will dynamically try to build a style object (which is not statically analyzable).

So yeah this feature would be nice to have and doable, just I think not as nice as the wrapper components.

**Comment by zippyui-react** [comment]
This is the exact same feature that came to mind as well. Would be nice if we could implement this for all inline styles, not just for the wrapper components you have specified (and which are really fine, as they correspond to display property values)

**Comment by edygar** [comment]
@petehunt, so, how are we supposed to style our links `<a/>` and have it propagated to stylesheet?

**Comment by petehunt** [comment]
@edygar Composition + cascade: `<InlineBlock color="..."><a href="...">...</a></InlineBlock>`

I still think the cascade kind of sucks and it'd be better to nest `<InlineBlock>` inside `<a>` but HTML isn't perfect :)

Separates the concerns of styling with the concern of click behavior and semantics, IMO :)

**Comment by threepointone** [comment]
How about 
```js 
<InlineBlock tag='a' color="..." props={{href: '...'}}> ... </InlineBlock>
```

**Comment by meyer** [comment]
Since the tag/component can now be specified with the `component` prop, I’m going to assume this issue is ok to close.
