### ISSUE TITLE
React 15 doesn't appear to work

### ISSUE THREAD

**Issue by ryanflorence** [petehunt/jsxstyle#23]
In React 0.14:

```js
import React from 'react'
import { render } from 'react-dom'
import { Flex, Block } from 'jsxstyle'

class App extends React.Component {
  render() {
    return (
      <Flex>
        <Block>One</Block>
        <Block>Main!</Block>
      </Flex>
    )
  }
}

render(<App/>, document.getElementById('app'))
```

Gives me this html output:

```html
<div style="display:flex;display:-webkit-flex;display:-ms-flexbox;" data-reactid=".0">
  <div style="display:block;" data-reactid=".0.0">One</div>
  <div style="display:block;" data-reactid=".0.1">Two</div>
</div>
```

And displays in a row, as expected.

With React 15, I get this HTML:

```html
<div data-reactroot="">
  <div style="display: block;">One</div>
  <div style="display: block;">Two</div>
</div>
```

And, as you can expect, it doesn't look correct because the top node doesn't get the style. I thought maybe something was up w/ the root node not working, but even deeper components still don't get the style applied.

**Comment by ryanflorence** [comment]
I won't have the time to dig into this right now, so I'm just going back to 0.14. Maybe in a few weeks I'll resurface and be able to take a peek at why this isn't working, might be really simple.

**Comment by meyer** [comment]
@ryanflorence looks like the issue is due to the move from `innerHTML` to `createElement` in React 15:

https://github.com/facebook/react/issues/2020#issuecomment-123402094

**Comment by meyer** [comment]
Hmm, looks like `CSSPropertyOperations.createMarkupForStyles` is doing the right thing. I’m guessing it’s `createElement`.

![image](https://cloud.githubusercontent.com/assets/13781/15699939/b0207a66-2785-11e6-9067-a6d3d67cac1a.png)

**Comment by meyer** [comment]
Oh hey, looks like this was already discussed here: https://github.com/petehunt/jsxstyle/issues/21

**Comment by meyer** [comment]
Looks like a combination of all of the above. When I’m hot reloading and I add a semicolon followed by anything else to a style value, `createMarkupForStyles` complains and refuses to update the inline CSS. Upon refresh, the display prop is no longer set.

![image](https://cloud.githubusercontent.com/assets/13781/15700262/d2dcf604-2787-11e6-8a51-d56e32000b9d.png)

The good news is that the problem goes away with the style tag changes in master.

**Comment by ryanflorence** [comment]
Looks like installing from github (`npm install petehunt/jsxstyle`) works with react 15.
