### ISSUE TITLE
@petehunt

### ISSUE THREAD

**Issue by taxiowa** [petehunt/jsxstyle#26]
I know I am in the wrong place, but my son has a Masters degree in Education and is thinking of changing careers.  He is interested in coding boot camp.  He is 26 and very smart and is currently an AD of high school.  I was wondering if this was worthwhile. @petehunt

**Comment by petehunt** [comment]
Hi @taxiowa - I think it is probably worthwhile. Happy to discuss via email at floydophone at gmail dot com, but GitHub issues aren't the place :)
