### ISSUE TITLE
Make style extraction - and thus `contextify` dependency - optional

### ISSUE THREAD

**Issue by burmisov** [petehunt/jsxstyle#5]
Maybe that's too early an optimization for this awesome module right now, but `contextify` needs a compilation build step which renders the whole thing problematic in terms of xplat'ness.
As far as the core run-time functionality is pure JS, may be it would be better to have the rest fancy and dev-time stuff optional (I mean dev-time of the projects using this module, not this module dev time :) )

**Comment by petehunt** [comment]
The rest is optional -- just turn off the webpack loader :)

**Comment by petehunt** [comment]
fixed contextify dep
