### ISSUE TITLE
For "Open Areas of Work" are you planning updates?

### ISSUE THREAD

**Issue by paulwehner** [petehunt/jsxstyle#6]
>>The reference webpack loader is hacky, exposes internal paths, is not optimized for production, and doesn't work with extract-text-plugin.

Was just curious if you are currently planning on optimizing the loader for production? If so do you have an approx timeline.

**Comment by petehunt** [comment]
I am not planning on working on an optimizer in the near future. I have not found there to be any performance problems with the purely inline styles based approach in practice. In theory there may be, and this repo serves to prove that it is possible to fix these theoretical performance issues.

Closing this out but I would be happy to accept a PR that adds even a most basic optimizer.

**Comment by paulwehner** [comment]
Thanks for letting me know!

So if I were to start developing an app with this library would you suggest that for development I use:

{test: /\.js$/, loader: 'jsx-loader?harmony!' + path.join(__dirname, 'node_modules', 'jsxstyle', 'lib', 'webpackLoader.js') + '?LayoutConstants=' + path.join(__dirname, 'LayoutConstants.js')}

Because as you mentioned "It also makes the web inspector harder to use since you can't update all instances of a component on the page simultaneously."

But when putting it into production switch back to:

{test: /\.js$/, loader: 'jsx-loader?harmony'},

And just use inline styles? To back-up your in practice point, the guys who are developing Radium mentioned that when you gzip your files, the size difference isn't significant even if you have a component that repeats many times on the page.

---

FYI - There is a reddit thread happening at the moment that discusses your library: http://www.reddit.com/r/reactjs/comments/344e0o/what_do_you_you_guys_think_of_petehuntjsxstyle_is/
